
services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0.40
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
       - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: frankmoreano
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      - spring
  msvc-usuarios:
    container_name: msvc-usuarios
    #build:
      #context: ./
      #dockerfile: ./msvc-usuarios/Dockerfile
    image: frankdc07/usuarios:latest
    ports:
      - "8001:8001"
    #env_file: ./msvc-usuarios/.env
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: adminadmin
      CURSOS_URL: msvc-cursos:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  msvc-cursos:
    container_name: msvc-cursos
    #build:
    #  context: ./
    #  dockerfile: ./msvc-cursos/Dockerfile
    image: frankdc07/cursos:latest
    ports:
      - "8002:8002"
    #env_file: ./msvc-cursos/.env
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: frankmoreano
      DB_PASSWORD: postgres
      USUARIOS_URL: msvc-usuarios:8001
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always

networks:
  spring:
    external: true

volumes:
  data-mysql:
    external: true
  data-postgres:
    external: true