apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  db_username: cm9vdA==
  db_password: YWRtaW5hZG1pbg==
---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  db_username: ZnJhbmttb3JlYW5v
  db_password: cG9zdGdyZXM=